name: Convert Videos to GIFs

on:
  push:
    branches: ['main']
    paths:
      - 'assets/**'
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test ci tags'

jobs:
  convert-videos:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Run video converter script
        run: |
          chmod +x ./video-converter.sh
          ./video-converter.sh

      - name: Commit and push changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add assets
          current_date=$(date +"%Y-%m-%d")
          git commit -m "ci: convert videos to GIF (Date: $current_date)" -a || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
