/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as CmtRouteImport } from './routes/cmt'
import { Route as ApiRouteImport } from './routes/api'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppsIndexRouteImport } from './routes/apps/index'
import { Route as AppsTypewriterRouteImport } from './routes/apps/typewriter'
import { Route as AppsReceiptRouteImport } from './routes/apps/receipt'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CmtRoute = CmtRouteImport.update({
  id: '/cmt',
  path: '/cmt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsIndexRoute = AppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsTypewriterRoute = AppsTypewriterRouteImport.update({
  id: '/apps/typewriter',
  path: '/apps/typewriter',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsReceiptRoute = AppsReceiptRouteImport.update({
  id: '/apps/receipt',
  path: '/apps/receipt',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api': typeof ApiRoute
  '/cmt': typeof CmtRoute
  '/profile': typeof ProfileRoute
  '/apps/receipt': typeof AppsReceiptRoute
  '/apps/typewriter': typeof AppsTypewriterRoute
  '/apps': typeof AppsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api': typeof ApiRoute
  '/cmt': typeof CmtRoute
  '/profile': typeof ProfileRoute
  '/apps/receipt': typeof AppsReceiptRoute
  '/apps/typewriter': typeof AppsTypewriterRoute
  '/apps': typeof AppsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api': typeof ApiRoute
  '/cmt': typeof CmtRoute
  '/profile': typeof ProfileRoute
  '/apps/receipt': typeof AppsReceiptRoute
  '/apps/typewriter': typeof AppsTypewriterRoute
  '/apps/': typeof AppsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/api'
    | '/cmt'
    | '/profile'
    | '/apps/receipt'
    | '/apps/typewriter'
    | '/apps'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/api'
    | '/cmt'
    | '/profile'
    | '/apps/receipt'
    | '/apps/typewriter'
    | '/apps'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/api'
    | '/cmt'
    | '/profile'
    | '/apps/receipt'
    | '/apps/typewriter'
    | '/apps/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ApiRoute: typeof ApiRoute
  CmtRoute: typeof CmtRoute
  ProfileRoute: typeof ProfileRoute
  AppsReceiptRoute: typeof AppsReceiptRoute
  AppsTypewriterRoute: typeof AppsTypewriterRoute
  AppsIndexRoute: typeof AppsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cmt': {
      id: '/cmt'
      path: '/cmt'
      fullPath: '/cmt'
      preLoaderRoute: typeof CmtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/': {
      id: '/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/typewriter': {
      id: '/apps/typewriter'
      path: '/apps/typewriter'
      fullPath: '/apps/typewriter'
      preLoaderRoute: typeof AppsTypewriterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/receipt': {
      id: '/apps/receipt'
      path: '/apps/receipt'
      fullPath: '/apps/receipt'
      preLoaderRoute: typeof AppsReceiptRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ApiRoute: ApiRoute,
  CmtRoute: CmtRoute,
  ProfileRoute: ProfileRoute,
  AppsReceiptRoute: AppsReceiptRoute,
  AppsTypewriterRoute: AppsTypewriterRoute,
  AppsIndexRoute: AppsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
