/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as GithubRouteImport } from './routes/github'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CmtRouteImport } from './routes/cmt'
import { Route as ApiRouteImport } from './routes/api'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AppsIndexRouteImport } from './routes/apps/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AppsTypewriterRouteImport } from './routes/apps/typewriter'
import { Route as AppsReceiptRouteImport } from './routes/apps/receipt'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/timeline.lazy').then((d) => d.Route))
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/resume.lazy').then((d) => d.Route))
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/projects.lazy').then((d) => d.Route))
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/profile.lazy').then((d) => d.Route))
const GithubRoute = GithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/github.lazy').then((d) => d.Route))
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/contact.lazy').then((d) => d.Route))
const CmtRoute = CmtRouteImport.update({
  id: '/cmt',
  path: '/cmt',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/cmt.lazy').then((d) => d.Route))
const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/api.lazy').then((d) => d.Route))
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/blog/index.lazy').then((d) => d.Route))
const AppsIndexRoute = AppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/blog/$slug.lazy').then((d) => d.Route))
const AppsTypewriterRoute = AppsTypewriterRouteImport.update({
  id: '/apps/typewriter',
  path: '/apps/typewriter',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/apps/typewriter.lazy').then((d) => d.Route),
)
const AppsReceiptRoute = AppsReceiptRouteImport.update({
  id: '/apps/receipt',
  path: '/apps/receipt',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/apps/receipt.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api': typeof ApiRoute
  '/cmt': typeof CmtRoute
  '/contact': typeof ContactRoute
  '/github': typeof GithubRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/resume': typeof ResumeRoute
  '/timeline': typeof TimelineRoute
  '/apps/receipt': typeof AppsReceiptRoute
  '/apps/typewriter': typeof AppsTypewriterRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/apps': typeof AppsIndexRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api': typeof ApiRoute
  '/cmt': typeof CmtRoute
  '/contact': typeof ContactRoute
  '/github': typeof GithubRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/resume': typeof ResumeRoute
  '/timeline': typeof TimelineRoute
  '/apps/receipt': typeof AppsReceiptRoute
  '/apps/typewriter': typeof AppsTypewriterRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/apps': typeof AppsIndexRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api': typeof ApiRoute
  '/cmt': typeof CmtRoute
  '/contact': typeof ContactRoute
  '/github': typeof GithubRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/resume': typeof ResumeRoute
  '/timeline': typeof TimelineRoute
  '/apps/receipt': typeof AppsReceiptRoute
  '/apps/typewriter': typeof AppsTypewriterRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/apps/': typeof AppsIndexRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/api'
    | '/cmt'
    | '/contact'
    | '/github'
    | '/profile'
    | '/projects'
    | '/resume'
    | '/timeline'
    | '/apps/receipt'
    | '/apps/typewriter'
    | '/blog/$slug'
    | '/apps'
    | '/blog'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/api'
    | '/cmt'
    | '/contact'
    | '/github'
    | '/profile'
    | '/projects'
    | '/resume'
    | '/timeline'
    | '/apps/receipt'
    | '/apps/typewriter'
    | '/blog/$slug'
    | '/apps'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/api'
    | '/cmt'
    | '/contact'
    | '/github'
    | '/profile'
    | '/projects'
    | '/resume'
    | '/timeline'
    | '/apps/receipt'
    | '/apps/typewriter'
    | '/blog/$slug'
    | '/apps/'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ApiRoute: typeof ApiRoute
  CmtRoute: typeof CmtRoute
  ContactRoute: typeof ContactRoute
  GithubRoute: typeof GithubRoute
  ProfileRoute: typeof ProfileRoute
  ProjectsRoute: typeof ProjectsRoute
  ResumeRoute: typeof ResumeRoute
  TimelineRoute: typeof TimelineRoute
  AppsReceiptRoute: typeof AppsReceiptRoute
  AppsTypewriterRoute: typeof AppsTypewriterRoute
  BlogSlugRoute: typeof BlogSlugRoute
  AppsIndexRoute: typeof AppsIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github': {
      id: '/github'
      path: '/github'
      fullPath: '/github'
      preLoaderRoute: typeof GithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cmt': {
      id: '/cmt'
      path: '/cmt'
      fullPath: '/cmt'
      preLoaderRoute: typeof CmtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/': {
      id: '/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/typewriter': {
      id: '/apps/typewriter'
      path: '/apps/typewriter'
      fullPath: '/apps/typewriter'
      preLoaderRoute: typeof AppsTypewriterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/receipt': {
      id: '/apps/receipt'
      path: '/apps/receipt'
      fullPath: '/apps/receipt'
      preLoaderRoute: typeof AppsReceiptRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ApiRoute: ApiRoute,
  CmtRoute: CmtRoute,
  ContactRoute: ContactRoute,
  GithubRoute: GithubRoute,
  ProfileRoute: ProfileRoute,
  ProjectsRoute: ProjectsRoute,
  ResumeRoute: ResumeRoute,
  TimelineRoute: TimelineRoute,
  AppsReceiptRoute: AppsReceiptRoute,
  AppsTypewriterRoute: AppsTypewriterRoute,
  BlogSlugRoute: BlogSlugRoute,
  AppsIndexRoute: AppsIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
